//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipe()
        {
            this.userfavorites = new HashSet<userfavorite>();
        }
    
        public string recipe_id { get; set; }
        public string image_url { get; set; }
        public string source_url { get; set; }
        public string f2f_url { get; set; }
        public string title { get; set; }
        public string publisher { get; set; }
        public string publisher_url { get; set; }
        public Nullable<double> social_rank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userfavorite> userfavorites { get; set; }
    }
}
